// ============================================================
// Éclat Institute — Official Institutional Courses & Fee Registry
// Single authoritative source of truth across Landing, Catalog, 
// E-Reader, Fees Management, and SIMS Invoicing.
// ============================================================

export interface CourseProgram {
  id: string
  title: string
  shortTitle: string
  category: 'Tech & Programming' | 'Data Science & Research' | 'Computer & Digital Skills' | 'Business Tech & Accounting' | 'Languages & Communication' | 'Creative Arts & Design' | 'Cambridge International (Years 9-11)' | 'Pearson Edexcel International (Years 9-11)' | string
  tag: string
  tagColor: string
  duration: string
  durationWeeks: number
  schedule: string
  feeUsd: number
  feeKes: number
  feeDisplay: string
  originalFeeUsd: number
  discountBadge: string
  installmentText: string
  instructor: string
  schoolId?: string
  schoolName?: string
  departmentId: string
  departmentName: string
  yearLevel?: 'Year 9' | 'Year 10' | 'Year 11' | 'Tertiary' | 'All Years' | string
  examBoard?: 'Cambridge (CAIE)' | 'Pearson Edexcel' | 'Professional' | string
  syllabusCode?: string
  careerOutcome: string
  skills: string[]
  icon: string
  bestseller?: boolean
  popular?: boolean
  rating: number
  ratingCount: number
  studentsEnrolled: number
  syllabus: {
    week: string
    topic: string
    practicalLab: string
  }[]
}

export const OFFICIAL_COURSES: CourseProgram[] = [
  // 1. Full-Stack Web Development
  {
    id: 'c-coding',
    title: 'Full-Stack Web Development & Modern JavaScript (React 19 & Node.js)',
    shortTitle: 'Full-Stack Web Dev (React 19)',
    category: 'Tech & Programming',
    tag: '💻 High-Salary Tech Career',
    tagColor: '#6366f1',
    duration: '12 Weeks (3 Months)',
    durationWeeks: 12,
    schedule: 'All Shifts: Early Morning, Late Morning, Midday, Afternoon, Evening & Night',
    feeUsd: 120,
    feeKes: 15500,
    feeDisplay: '$120 / KES 15,500',
    originalFeeUsd: 240,
    discountBadge: '50% OFF',
    installmentText: '2 installments of $60 (KES 7,750)',
    instructor: 'Eng. Alex Mwangi • Senior Software Architect',
    departmentId: 'dept-swe',
    departmentName: 'School of Software Engineering & Web Development',
    careerOutcome: 'Junior Full-Stack Developer • Frontend React Engineer • Cloud Tech Contractor',
    skills: ['React 19 & JavaScript ES6+', 'Node.js & Express APIs', 'PostgreSQL & Supabase Cloud', 'Tailwind CSS & Git GitHub', 'Full-Stack Portfolio Project'],
    icon: '💻',
    bestseller: true,
    popular: true,
    rating: 4.95,
    ratingCount: 1420,
    studentsEnrolled: 3850,
    syllabus: [
      { week: 'Week 1-3', topic: 'HTML5 Semantic Layouts, Modern Tailwind CSS & JavaScript ES6+', practicalLab: 'Live coding responsive web landing pages and portfolio projects.' },
      { week: 'Week 4-6', topic: 'React 19 State, Hooks, Component Architectures & APIs', practicalLab: 'Building dynamic interactive dashboards with real-time API integrations.' },
      { week: 'Week 7-9', topic: 'Node.js Backend, Express REST APIs & Authentication', practicalLab: 'Developing secure authentication systems and CRUD endpoints.' },
      { week: 'Week 10-12', topic: 'PostgreSQL Relational DBs & Cloud Server Deployment', practicalLab: 'Deploying full-stack production applications to Vercel and cloud containers.' },
    ],
  },

  // 2. Python Programming & Data Analytics
  {
    id: 'c-python',
    title: 'Python Programming, SQL & Data Analytics Masterclass',
    shortTitle: 'Python & Data Analytics',
    category: 'Data Science & Research',
    tag: '🐍 Data & AI Fundamentals',
    tagColor: '#0284c7',
    duration: '8 Weeks (2 Months)',
    durationWeeks: 8,
    schedule: 'All Shifts: Early Morning, Late Morning, Midday, Afternoon, Evening & Night',
    feeUsd: 95,
    feeKes: 12500,
    feeDisplay: '$95 / KES 12,500',
    originalFeeUsd: 190,
    discountBadge: '50% OFF',
    installmentText: '2 installments of $48 (KES 6,250)',
    instructor: 'Dr. Brian Ochieng • Lead Data Scientist',
    departmentId: 'dept-data',
    departmentName: 'Department of Python Programming & Data Analytics',
    careerOutcome: 'Data Analyst • Business Intelligence Specialist • Junior Python Developer',
    skills: ['Python Syntax & OOP', 'Pandas & NumPy Data Wrangling', 'SQL Queries & Relational DBs', 'Matplotlib & Seaborn Visualizations', 'Power BI Dashboards'],
    icon: '🐍',
    bestseller: true,
    popular: true,
    rating: 4.88,
    ratingCount: 980,
    studentsEnrolled: 2420,
    syllabus: [
      { week: 'Week 1-2', topic: 'Python Programming Fundamentals & Data Structures', practicalLab: 'Writing Python scripts, automation loops, and algorithmic problem solving.' },
      { week: 'Week 3-4', topic: 'SQL Relational Queries & Database Aggregations', practicalLab: 'Querying complex multi-table datasets, filtering, and JOIN operations.' },
      { week: 'Week 5-6', topic: 'Data Wrangling & Statistical Analysis with Pandas', practicalLab: 'Cleaning messy real-world corporate data and handling missing metrics.' },
      { week: 'Week 7-8', topic: 'Interactive Visualizations & Business Intelligence', practicalLab: 'Publishing interactive analytics dashboards and executive reports.' },
    ],
  },

  // 3. Cybersecurity & Defensive Ops
  {
    id: 'c-cyber',
    title: 'Cybersecurity Fundamentals, Ethical Hacking & Defensive Ops',
    shortTitle: 'Cybersecurity & Ethical Hacking',
    category: 'Tech & Programming',
    tag: '🛡️ Security & Defense',
    tagColor: '#dc2626',
    duration: '6 Weeks',
    durationWeeks: 6,
    schedule: 'All Shifts: Early Morning, Late Morning, Midday, Afternoon, Evening & Night',
    feeUsd: 89,
    feeKes: 11500,
    feeDisplay: '$89 / KES 11,500',
    originalFeeUsd: 175,
    discountBadge: '49% OFF',
    installmentText: '2 installments of $45 (KES 5,750)',
    instructor: 'Mr. David Kiprono, CISSP • Cybersecurity Consultant',
    departmentId: 'dept-cyber',
    departmentName: 'Department of Cybersecurity & Network Defense',
    careerOutcome: 'Junior SOC Analyst • IT Security Auditor • Network Security Admin',
    skills: ['Network Security & OSI Model', 'Vulnerability Assessment & Wireshark', 'Ethical Hacking Fundamentals', 'Firewalls & Encryption Standards', 'Incident Response Audits'],
    icon: '🛡️',
    bestseller: false,
    popular: true,
    rating: 4.90,
    ratingCount: 640,
    studentsEnrolled: 1650,
    syllabus: [
      { week: 'Week 1-2', topic: 'Networking Protocols, TCP/IP, OSI & Firewall Architecture', practicalLab: 'Packet sniffing with Wireshark and analyzing network traffic security.' },
      { week: 'Week 3-4', topic: 'Common Cyber Attack Vectors, Malware & Social Engineering', practicalLab: 'Identifying phishing payloads, vulnerability scanning, and risk reports.' },
      { week: 'Week 5-6', topic: 'Defensive Hardening, Cryptography & Incident Response', practicalLab: 'Configuring secure server policies, SSL/TLS, and security audit checklists.' },
    ],
  },

  // 4. Data Analysis with SPSS, STATA & R Studio
  {
    id: 'c-spss-r',
    title: 'Data Analysis with SPSS, STATA & R Studio Masterclass',
    shortTitle: 'SPSS, STATA & R Studio',
    category: 'Data Science & Research',
    tag: '📊 Academic & M&E Research',
    tagColor: '#10b981',
    duration: '6 Weeks',
    durationWeeks: 6,
    schedule: 'All Shifts: Early Morning, Late Morning, Midday, Afternoon, Evening & Night',
    feeUsd: 85,
    feeKes: 11000,
    feeDisplay: '$85 / KES 11,000',
    originalFeeUsd: 170,
    discountBadge: '50% OFF',
    installmentText: '2 installments of $45 (KES 5,500)',
    instructor: 'Dr. Brian Ochieng • Quantitative Research Fellow',
    departmentId: 'dept-data',
    departmentName: 'Department of Python Programming & Data Analytics',
    careerOutcome: 'Monitoring & Evaluation (M&E) Specialist • Academic Researcher • Biostatistician',
    skills: ['SPSS Regression & Coding', 'STATA Econometric Panel Data', 'R Studio & ggplot2', 'Hypothesis Testing (ANOVA, Chi-Sq)', 'APA Table Formatting'],
    icon: '📊',
    bestseller: true,
    popular: true,
    rating: 4.85,
    ratingCount: 720,
    studentsEnrolled: 1890,
    syllabus: [
      { week: 'Week 1-2', topic: 'Descriptive Statistics & SPSS Survey Coding', practicalLab: 'Clean and code multi-indicator survey questionnaires.' },
      { week: 'Week 3-4', topic: 'Hypothesis Testing (ANOVA, Chi-Square, T-Tests)', practicalLab: 'Conduct cross-tabulation and factor analysis on demographics.' },
      { week: 'Week 5', topic: 'STATA Econometric & Panel Regression Modeling', practicalLab: 'Run fixed and random effects on economic metrics.' },
      { week: 'Week 6', topic: 'R Studio Data Visualization with ggplot2', practicalLab: 'Generate publication-ready APA thesis tables and charts.' },
    ],
  },

  // 5. Comprehensive Computer Packages & Digital Skills
  {
    id: 'c-comp',
    title: 'Comprehensive Computer Packages & Modern Digital Skills',
    shortTitle: 'Computer Packages & Digital Skills',
    category: 'Computer & Digital Skills',
    tag: '⚡ Foundational Tech Skills',
    tagColor: '#f59e0b',
    duration: '4-6 Weeks',
    durationWeeks: 4,
    schedule: 'All Shifts: Early Morning, Late Morning, Midday, Afternoon, Evening & Night',
    feeUsd: 45,
    feeKes: 6000,
    feeDisplay: '$45 / KES 6,000',
    originalFeeUsd: 90,
    discountBadge: '50% OFF',
    installmentText: 'Single payment of $45 (KES 6,000)',
    instructor: 'Mr. James Mutua • Certified Microsoft Specialist',
    departmentId: 'dept-comp',
    departmentName: 'Department of Computer Applications & Digital Skills',
    careerOutcome: 'Executive Virtual Assistant • Data Entry Clerk • Office Administrative Secretary',
    skills: ['Microsoft Word & Docs Formatting', 'Advanced Excel Formulas & Charts', 'PowerPoint Slide Presentations', 'Google Workspace & Cloud Storage', 'Touch Typing & Email Etiquette'],
    icon: '🖥️',
    bestseller: true,
    popular: true,
    rating: 4.92,
    ratingCount: 1840,
    studentsEnrolled: 5120,
    syllabus: [
      { week: 'Week 1', topic: 'Computer Fundamentals, Operating Systems & Fast Typing', practicalLab: 'Mastering keyboard shortcuts, file hierarchies, and 45+ WPM typing.' },
      { week: 'Week 2', topic: 'Microsoft Word & Professional Document Typography', practicalLab: 'Formatting institutional executive memos, reports, and resumes.' },
      { week: 'Week 3', topic: 'Advanced Microsoft Excel (VLOOKUP, IF, Pivot Tables)', practicalLab: 'Building automated sales trackers, payroll sheets, and visual charts.' },
      { week: 'Week 4', topic: 'Google Workspace, Cloud Backups & Email Productivity', practicalLab: 'Managing corporate calendars, Google Sheets collaboration, and cloud drives.' },
    ],
  },

  // 6. Computerized Accounting (QuickBooks & International Tax)
  {
    id: 'c-accounting',
    title: 'Computerized Accounting (QuickBooks & International Tax / iTax)',
    shortTitle: 'Computerized Accounting (QuickBooks)',
    category: 'Business Tech & Accounting',
    tag: '📈 Finance & Bookkeeping',
    tagColor: '#059669',
    duration: '4 Weeks',
    durationWeeks: 4,
    schedule: 'All Shifts: Early Morning, Late Morning, Midday, Afternoon, Evening & Night',
    feeUsd: 65,
    feeKes: 8500,
    feeDisplay: '$65 / KES 8,500',
    originalFeeUsd: 130,
    discountBadge: '50% OFF',
    installmentText: 'Single payment of $65 (KES 8,500)',
    instructor: 'Mrs. Grace Wanjiku, CPA-K • Financial Systems Director',
    departmentId: 'dept-biztech',
    departmentName: 'Department of Business Tech & Computerized Accounting',
    careerOutcome: 'Assistant Accountant • QuickBooks Bookkeeper • Tax Compliance Assistant',
    skills: ['QuickBooks Online & Desktop Setup', 'Chart of Accounts & Ledgers', 'Bank Reconciliations & Invoicing', 'VAT, PAYE & Corporate Tax Filing', 'Profit & Loss Financial Reporting'],
    icon: '📊',
    bestseller: false,
    popular: true,
    rating: 4.86,
    ratingCount: 430,
    studentsEnrolled: 1180,
    syllabus: [
      { week: 'Week 1', topic: 'Introduction to Digital Bookkeeping & Chart of Accounts', practicalLab: 'Setting up new corporate entities in QuickBooks Online.' },
      { week: 'Week 2', topic: 'Customer Invoicing, Accounts Receivable & Vendor Ledgers', practicalLab: 'Issuing invoices, processing credit notes, and recording payments.' },
      { week: 'Week 3', topic: 'Bank Reconciliations & Petty Cash Management', practicalLab: 'Reconciling live bank feeds and matching transactional entries.' },
      { week: 'Week 4', topic: 'Tax Compliance (VAT, PAYE) & Financial Statement Generation', practicalLab: 'Filing tax returns and generating Balance Sheet & P&L statements.' },
    ],
  },

  // 7. IELTS Academic & General Prep
  {
    id: 'c-ielts',
    title: 'IELTS Academic & General Exam Prep (Target Band 7.5 - 9.0)',
    shortTitle: 'IELTS Exam Prep (Band 7.5 - 9.0)',
    category: 'Languages & Communication',
    tag: '🌍 Global Study & Relocation',
    tagColor: '#7c3aed',
    duration: '4-6 Weeks',
    durationWeeks: 4,
    schedule: 'All Shifts: Early Morning, Late Morning, Midday, Afternoon, Evening & Night',
    feeUsd: 85,
    feeKes: 11000,
    feeDisplay: '$85 / KES 11,000',
    originalFeeUsd: 170,
    discountBadge: '50% OFF',
    installmentText: '2 installments of $45 (KES 5,500)',
    instructor: 'Dr. Sarah Jenkins • British Council Certified IELTS Trainer',
    departmentId: 'dept-ielts',
    departmentName: 'Department of IELTS & International Test Prep',
    careerOutcome: 'UK/Canada/US University Admissions • Express Entry Work Permits • Global Nursing Licensure',
    skills: ['Listening Section Speed Strategy', 'Academic Reading Skimming & Scanning', 'Task 1 & Task 2 Essay Templates', 'Speaking Fluency & Accent Reduction', 'Full Mock Exam Simulation'],
    icon: '🌍',
    bestseller: true,
    popular: true,
    rating: 4.96,
    ratingCount: 1120,
    studentsEnrolled: 3100,
    syllabus: [
      { week: 'Week 1', topic: 'IELTS Exam Structure & Listening Section Mastery', practicalLab: 'Listening audio speed drills and error elimination tactics.' },
      { week: 'Week 2', topic: 'Academic & General Reading Tactics (Skimming & Scanning)', practicalLab: 'Solving True/False/Not Given and paragraph heading questions.' },
      { week: 'Week 3', topic: 'Writing Task 1 & Task 2 Structured Essay Blueprints', practicalLab: 'Live essay writing, vocabulary enhancement, and structural grading.' },
      { week: 'Week 4', topic: '1-on-1 Speaking Interviews & Full Computer-Delivered Mock', practicalLab: 'Real-time mock interview evaluation and comprehensive score feedback.' },
    ],
  },

  // 8. English Language Fluency & Corporate Speaking
  {
    id: 'c-english',
    title: 'English Language Fluency & Corporate Public Speaking',
    shortTitle: 'English Fluency & Speaking',
    category: 'Languages & Communication',
    tag: '🗣️ Confidence & Leadership',
    tagColor: '#0891b2',
    duration: '6-8 Weeks',
    durationWeeks: 6,
    schedule: 'All Shifts: Early Morning, Late Morning, Midday, Afternoon, Evening & Night',
    feeUsd: 55,
    feeKes: 7000,
    feeDisplay: '$55 / KES 7,000',
    originalFeeUsd: 110,
    discountBadge: '50% OFF',
    installmentText: 'Single payment of $55 (KES 7,000)',
    instructor: 'Mme. Claire Dubois • Head of Modern Languages',
    departmentId: 'dept-lang',
    departmentName: 'Department of English & Modern Languages',
    careerOutcome: 'Corporate Spokesperson • Customer Relations Officer • International Presenter',
    skills: ['Accent Neutralization & Pronunciation', 'Business Vocabulary & Email Writing', 'Overcoming Stage Fright & Pauses', 'Impromptu Speech Construction', 'Executive Meeting Leadership'],
    icon: '🗣️',
    bestseller: false,
    popular: true,
    rating: 4.87,
    ratingCount: 540,
    studentsEnrolled: 1450,
    syllabus: [
      { week: 'Week 1-2', topic: 'Phonetics, Vowel Articulation & Neutral Pronunciation', practicalLab: 'Live audio recording critique and speech pitch exercises.' },
      { week: 'Week 3-4', topic: 'Professional Grammar, Vocabulary & Business Communication', practicalLab: 'Crafting persuasive corporate proposals and executive emails.' },
      { week: 'Week 5-6', topic: 'Public Speaking, Presentations & Debate Mastery', practicalLab: 'Delivering live 5-minute virtual TED-style talks with feedback.' },
    ],
  },

  // 9. Foreign Languages (Arabic, French & German)
  {
    id: 'c-foreign-lang',
    title: 'Foreign Languages Certification (Arabic, French & German)',
    shortTitle: 'Arabic, French & German',
    category: 'Languages & Communication',
    tag: '🌴 Multilingual Career',
    tagColor: '#d97706',
    duration: '8 Weeks',
    durationWeeks: 8,
    schedule: 'All Shifts: Early Morning, Late Morning, Midday, Afternoon, Evening & Night',
    feeUsd: 79,
    feeKes: 10000,
    feeDisplay: '$79 / KES 10,000',
    originalFeeUsd: 160,
    discountBadge: '50% OFF',
    installmentText: '2 installments of $40 (KES 5,000)',
    instructor: 'Mme. Claire Dubois & Faculty Linguists',
    departmentId: 'dept-lang',
    departmentName: 'Department of English & Modern Languages',
    careerOutcome: 'Diplomatic Aide • International Flight Attendant • Multilingual Customer Consultant',
    skills: ['A1-A2 Common European Framework (CEFR)', 'Everyday Conversational Dialogues', 'Grammar Conjugation & Sentence Form', 'Listening Comprehension', 'Cultural Context & Idioms'],
    icon: '🌴',
    bestseller: false,
    popular: true,
    rating: 4.89,
    ratingCount: 380,
    studentsEnrolled: 980,
    syllabus: [
      { week: 'Week 1-2', topic: 'Alphabet, Phonology, Greetings & Self Introductions', practicalLab: 'Interactive roleplay conversations and audio drills.' },
      { week: 'Week 3-4', topic: 'Essential Everyday Vocabulary (Numbers, Time, Shopping, Directions)', practicalLab: 'Simulating real-life conversational scenarios.' },
      { week: 'Week 5-6', topic: 'Present & Past Tense Verb Conjugation & Sentence Rules', practicalLab: 'Writing short letters and structured conversational dialogues.' },
      { week: 'Week 7-8', topic: 'A1 Certification Readiness & Fluent Speaking Assessment', practicalLab: 'Live 1-on-1 language fluency evaluation with instructor.' },
    ],
  },
  // ============================================================
  // SCHOOL OF CAMBRIDGE INTERNATIONAL CURRICULUM (CAIE CENTER KE042)
  // Years 9 (Foundation Checkpoint), 10 (IGCSE Year 1), 11 (Exam Prep)
  // ============================================================

  // --- Cambridge Year 9 (Lower Secondary Foundation) ---
  {
    id: 'c-caie-y9-math',
    title: 'Cambridge Lower Secondary Mathematics 0862 (Year 9 Checkpoint Foundation)',
    shortTitle: 'Cambridge Math Year 9 (0862)',
    category: 'Cambridge International (Years 9-11)',
    tag: '🏛️ CAIE Year 9 Foundation',
    tagColor: '#0284c7',
    duration: '10 Weeks (Stage 9 Bridge)',
    durationWeeks: 10,
    schedule: 'Live Online Interactive Batches (Checkpoint Foundation)',
    feeUsd: 75,
    feeKes: 9750,
    feeDisplay: '$75 / KES 9,750',
    originalFeeUsd: 150,
    discountBadge: '50% OFF',
    installmentText: '2 installments of $38 (KES 4,875)',
    instructor: 'Dr. Michael Davies & Cambridge Certified Math Faculty',
    schoolId: 'school-cambridge',
    schoolName: 'School of Cambridge International Curriculum (CAIE)',
    departmentId: 'dept-caie-math-cs',
    departmentName: 'Department of Cambridge Mathematical & Computational Sciences',
    yearLevel: 'Year 9',
    examBoard: 'Cambridge (CAIE)',
    syllabusCode: '0862',
    careerOutcome: 'Stage 9 Checkpoint Distinction • Prerequisite Foundation for IGCSE 0580 Extended Math',
    skills: ['Algebraic Expressions & Linear Equations', 'Fractions, Decimals & Indices', '2D/3D Geometry & Transformations', 'Probability & Data Representations', 'Checkpoint Exam Speed Drills'],
    icon: '📐',
    popular: true,
    rating: 4.95,
    ratingCount: 380,
    studentsEnrolled: 890,
    syllabus: [
      { week: 'Week 1-2', topic: 'Indices, Standard Form, Scientific Notation & Surds Intro', practicalLab: 'Timed arithmetic and mental algebra speed challenges.' },
      { week: 'Week 3-4', topic: 'Linear Equations, Simultaneous Equations & Subject of Formula', practicalLab: 'Solving two-step algebraic balance problems.' },
      { week: 'Week 5-6', topic: 'Coordinate Geometry, Linear Graphs (y = mx + c) & Midpoints', practicalLab: 'Plotting gradient triangles and equation verifications.' },
      { week: 'Week 7-8', topic: 'Pythagoras Theorem, Area/Volume of Prisms & Cylinders', practicalLab: '3D geometrical dimension modeling worksheets.' },
      { week: 'Week 9-10', topic: 'Cambridge Stage 9 Checkpoint Mock Examination & Review', practicalLab: 'Full timed Stage 9 past paper simulation.' },
    ],
  },
  {
    id: 'c-caie-y9-science',
    title: 'Cambridge Lower Secondary Science 0893 (Year 9 Integrated Physics, Chem & Bio)',
    shortTitle: 'Cambridge Science Year 9 (0893)',
    category: 'Cambridge International (Years 9-11)',
    tag: '🔬 CAIE Year 9 Science',
    tagColor: '#10b981',
    duration: '10 Weeks (Stage 9 Bridge)',
    durationWeeks: 10,
    schedule: 'Live Online Lecture & Virtual Laboratory Simulations',
    feeUsd: 75,
    feeKes: 9750,
    feeDisplay: '$75 / KES 9,750',
    originalFeeUsd: 150,
    discountBadge: '50% OFF',
    installmentText: '2 installments of $38 (KES 4,875)',
    instructor: 'Eng. Sarah Jenkins & Dr. Anita Sharma',
    schoolId: 'school-cambridge',
    schoolName: 'School of Cambridge International Curriculum (CAIE)',
    departmentId: 'dept-caie-sciences',
    departmentName: 'Department of Cambridge Natural & Experimental Sciences',
    yearLevel: 'Year 9',
    examBoard: 'Cambridge (CAIE)',
    syllabusCode: '0893',
    careerOutcome: 'Stage 9 Science Checkpoint Mastery • Seamless Transition into IGCSE Physics, Chem & Bio',
    skills: ['Forces, Energy & Pressure Fundamentals', 'Periodic Table & Chemical Reactions', 'Photosynthesis & Human Organ Systems', 'Scientific Method & Virtual Lab Reports'],
    icon: '🔬',
    popular: true,
    rating: 4.93,
    ratingCount: 310,
    studentsEnrolled: 760,
    syllabus: [
      { week: 'Week 1-2', topic: 'Energy Transfer, Thermal Conduction & Density Calculations', practicalLab: 'Virtual lab density calculations for irregular solids.' },
      { week: 'Week 3-4', topic: 'Atoms, Elements, Reactivity Series & Acid-Base Neutralization', practicalLab: 'Reactivity series displacement reaction simulations.' },
      { week: 'Week 5-6', topic: 'Plant Biology, Respiration & Ecosystem Food Webs', practicalLab: 'Microscope slide analysis of plant stomata.' },
      { week: 'Week 7-8', topic: 'Electricity, Simple Circuits & Magnetism', practicalLab: 'Ohm’s law and series/parallel circuit measurements.' },
      { week: 'Week 9-10', topic: 'Stage 9 Checkpoint Past Paper Walkthrough & Assessment', practicalLab: 'Complete Paper 1 & Paper 2 mock exam.' },
    ],
  },
  {
    id: 'c-caie-y9-cs',
    title: 'Cambridge Lower Secondary Computing & Python Logic (Year 9 Pre-IGCSE)',
    shortTitle: 'Cambridge Computing Year 9',
    category: 'Cambridge International (Years 9-11)',
    tag: '💻 CAIE Year 9 Computing',
    tagColor: '#8b5cf6',
    duration: '8 Weeks (Pre-IGCSE Prep)',
    durationWeeks: 8,
    schedule: 'Interactive Coding Labs & Algorithmic Problem Solving',
    feeUsd: 70,
    feeKes: 9100,
    feeDisplay: '$70 / KES 9,100',
    originalFeeUsd: 140,
    discountBadge: '50% OFF',
    installmentText: '2 installments of $35 (KES 4,550)',
    instructor: 'Eng. Alex Mwangi • Cambridge Computing Specialist',
    schoolId: 'school-cambridge',
    schoolName: 'School of Cambridge International Curriculum (CAIE)',
    departmentId: 'dept-caie-math-cs',
    departmentName: 'Department of Cambridge Mathematical & Computational Sciences',
    yearLevel: 'Year 9',
    examBoard: 'Cambridge (CAIE)',
    careerOutcome: 'Solid Programming & Logical Foundations for IGCSE Computer Science 0478',
    skills: ['Binary & Hexadecimal Basics', 'Logic Gates & Truth Tables', 'Python Syntax (Variables, Loops, If/Else)', 'Algorithm Flowcharts & Pseudocode'],
    icon: '💻',
    popular: true,
    rating: 4.96,
    ratingCount: 290,
    studentsEnrolled: 690,
    syllabus: [
      { week: 'Week 1-2', topic: 'Binary Representation & Digital Storage Math', practicalLab: 'Base 2 and Base 16 conversions.' },
      { week: 'Week 3-4', topic: 'Logic Gates (AND, OR, NOT) & Algorithmic Flowcharts', practicalLab: 'Drawing standard flowchart symbols for decision branching.' },
      { week: 'Week 5-6', topic: 'Python Programming Essentials (Inputs, Data Types, Conditionals)', practicalLab: 'Coding interactive terminal calculators and number guessers.' },
      { week: 'Week 7-8', topic: 'Loops (While / For), Lists & Capstone Mini-Project', practicalLab: 'Building a console quiz application in Python.' },
    ],
  },

  // --- Cambridge Year 10 (IGCSE Year 1 - Core & Extended) ---
  {
    id: 'c-igcse-math',
    title: 'Cambridge IGCSE Mathematics 0580 (Year 10 Core & Extended Theory)',
    shortTitle: 'Cambridge Math Year 10 (0580)',
    category: 'Cambridge International (Years 9-11)',
    tag: '📐 CAIE Year 10 Math 0580',
    tagColor: '#0284c7',
    duration: '12 Weeks (Syllabus Part 1)',
    durationWeeks: 12,
    schedule: 'Live Online Interactive Batches (May/June & Oct/Nov Series)',
    feeUsd: 85,
    feeKes: 11050,
    feeDisplay: '$85 / KES 11,050',
    originalFeeUsd: 170,
    discountBadge: '50% OFF',
    installmentText: '2 installments of $43 (KES 5,525)',
    instructor: 'Dr. Michael Davies & Cambridge Certified Math Faculty',
    schoolId: 'school-cambridge',
    schoolName: 'School of Cambridge International Curriculum (CAIE)',
    departmentId: 'dept-caie-math-cs',
    departmentName: 'Department of Cambridge Mathematical & Computational Sciences',
    yearLevel: 'Year 10',
    examBoard: 'Cambridge (CAIE)',
    syllabusCode: '0580',
    careerOutcome: 'Target Grade 9 / 8 (A*) in Cambridge 0580 • Prerequisite for A-Level Math & STEM Degrees',
    skills: [
      'Number & Algebra Mastery',
      'Functions & Coordinate Geometry',
      'Trigonometry & Circle Theorems',
      'Vectors & Transformations',
      'Paper 2 & Paper 4 Exam Technique',
      'Past Paper Walkthroughs',
    ],
    icon: '📐',
    bestseller: true,
    popular: true,
    rating: 4.96,
    ratingCount: 520,
    studentsEnrolled: 1420,
    syllabus: [
      { week: 'Week 1-2', topic: 'Number, Standard Form, Percentages & Bounds', practicalLab: 'Paper 2 Speed & Accuracy drills with timed past paper questions.' },
      { week: 'Week 3-4', topic: 'Algebraic Manipulation, Quadratics, Sequences & Inequalities', practicalLab: 'Solving multi-step Paper 4 extended algebraic problem sheets.' },
      { week: 'Week 5-6', topic: 'Coordinate Geometry, Straight Line Graphs & Functions f(x)', practicalLab: 'Function composite mapping and inverse functions past paper workshops.' },
      { week: 'Week 7-8', topic: 'Trigonometry (Sine/Cosine Rules, Bearings, 3D Trig)', practicalLab: 'Mastering 3D Pythagoras and bearings diagram problems.' },
      { week: 'Week 9-10', topic: 'Vectors, Transformations & Circle Theorems', practicalLab: 'Vector geometric proof and matrix transformation mastery.' },
      { week: 'Week 11-12', topic: 'Probability, Statistics & Complete Mock Exam Simulations', practicalLab: 'Full timed Paper 2 & Paper 4 mock exams with examiner grade boundary report.' },
    ],
  },
  {
    id: 'c-igcse-physics',
    title: 'Cambridge IGCSE Physics 0625 (Year 10 Mechanics, Thermal & Waves)',
    shortTitle: 'Cambridge Physics Year 10 (0625)',
    category: 'Cambridge International (Years 9-11)',
    tag: '⚡ CAIE Year 10 Physics 0625',
    tagColor: '#6366f1',
    duration: '12 Weeks (Syllabus Part 1)',
    durationWeeks: 12,
    schedule: 'Live Online Lectures & Virtual Practical Simulations',
    feeUsd: 85,
    feeKes: 11050,
    feeDisplay: '$85 / KES 11,050',
    originalFeeUsd: 170,
    discountBadge: '50% OFF',
    installmentText: '2 installments of $43 (KES 5,525)',
    instructor: 'Eng. Sarah Jenkins • Oxford Cambridge Physics Specialist',
    schoolId: 'school-cambridge',
    schoolName: 'School of Cambridge International Curriculum (CAIE)',
    departmentId: 'dept-caie-sciences',
    departmentName: 'Department of Cambridge Natural & Experimental Sciences',
    yearLevel: 'Year 10',
    examBoard: 'Cambridge (CAIE)',
    syllabusCode: '0625',
    careerOutcome: 'Target Grade 9 / A* in Physics 0625 • Gateway to Engineering, Robotics & Medicine',
    skills: [
      'Motion, Forces & Energy Dynamics',
      'Thermal & Wave Properties',
      'Electricity, Magnetism & Circuits',
      'Nuclear Physics & Space Astronomy',
      'Paper 4 Extended Theory Tactics',
      'Paper 6 Alternative to Practical Lab Skills',
    ],
    icon: '⚛️',
    bestseller: true,
    popular: true,
    rating: 4.94,
    ratingCount: 460,
    studentsEnrolled: 1150,
    syllabus: [
      { week: 'Week 1-2', topic: 'Motion, Forces, Momentum, Pressure & Energy', practicalLab: 'Calculation workshops on F=ma, velocity-time graphs and hydraulic press.' },
      { week: 'Week 3-4', topic: 'Thermal Physics, Gas Laws & Specific Heat Capacity', practicalLab: 'Thermal transfer and particle model problem-solving.' },
      { week: 'Week 5-6', topic: 'Waves, Light, Optics, Sound & Electromagnetic Spectrum', practicalLab: 'Ray diagrams for lenses and Snell’s law refraction experiments.' },
      { week: 'Week 7-8', topic: 'Electricity, Ohm’s Law, Logic Gates & Electromagnetic Effects', practicalLab: 'Circuit analysis and transformer equation calculation drills.' },
      { week: 'Week 9-10', topic: 'Nuclear Physics, Radioactive Decay & Space Physics', practicalLab: 'Half-life graphical analysis and Doppler redshift exercises.' },
      { week: 'Week 11-12', topic: 'Paper 4 Theory & Paper 6 ATP Intensive Mock Series', practicalLab: 'Full mock paper analysis with Cambridge examiner marking criteria.' },
    ],
  },
  {
    id: 'c-igcse-chemistry',
    title: 'Cambridge IGCSE Chemistry 0620 (Year 10 States, Bonding & Stoichiometry)',
    shortTitle: 'Cambridge Chemistry Year 10 (0620)',
    category: 'Cambridge International (Years 9-11)',
    tag: '🧪 CAIE Year 10 Chem 0620',
    tagColor: '#10b981',
    duration: '12 Weeks (Syllabus Part 1)',
    durationWeeks: 12,
    schedule: 'Live Online Interactive Batches (May/June & Oct/Nov Series)',
    feeUsd: 85,
    feeKes: 11050,
    feeDisplay: '$85 / KES 11,050',
    originalFeeUsd: 170,
    discountBadge: '50% OFF',
    installmentText: '2 installments of $43 (KES 5,525)',
    instructor: 'Dr. Anita Sharma • Cambridge Senior Chemistry Examiner',
    schoolId: 'school-cambridge',
    schoolName: 'School of Cambridge International Curriculum (CAIE)',
    departmentId: 'dept-caie-sciences',
    departmentName: 'Department of Cambridge Natural & Experimental Sciences',
    yearLevel: 'Year 10',
    examBoard: 'Cambridge (CAIE)',
    syllabusCode: '0620',
    careerOutcome: 'Target Grade 9 / A* in Chem 0620 • Essential Foundation for Medicine, Pharmacy & BioTech',
    skills: [
      'Stoichiometry & The Mole Concept',
      'Electrochemistry & Chemical Energetics',
      'Rates of Reaction & Equilibrium',
      'Acids, Bases & Salt Preparation',
      'Organic Chemistry & Polymers',
      'Paper 6 Qualitative Analysis & Testing',
    ],
    icon: '🧪',
    popular: true,
    rating: 4.92,
    ratingCount: 390,
    studentsEnrolled: 890,
    syllabus: [
      { week: 'Week 1-2', topic: 'Particulate Nature of Matter, Bonding & Atomic Structure', practicalLab: 'Covalent vs ionic crystal lattice analysis drills.' },
      { week: 'Week 3-4', topic: 'Stoichiometry, Moles, Titration & Gas Volumes', practicalLab: 'Mastering the Mole calculation formula and empirical formula problems.' },
      { week: 'Week 5-6', topic: 'Electrochemistry, Electrolysis of Molten & Aqueous Salts', practicalLab: 'Predicting electrode products and half-equations.' },
      { week: 'Week 7-8', topic: 'Acids, Bases, Salts Preparation & Qualitative Analysis', practicalLab: 'Paper 6 cation, anion and gas identification flowcharts.' },
      { week: 'Week 9-10', topic: 'Organic Chemistry (Alkanes, Alkenes, Alcohols & Polymers)', practicalLab: 'Cracking, polymerization reactions and structural formula diagrams.' },
      { week: 'Week 11-12', topic: 'Past Paper Marathons & Mock Examination', practicalLab: 'Timed Paper 2 (MCQ), Paper 4 (Extended) & Paper 6 (ATP) with mark schemes.' },
    ],
  },
  {
    id: 'c-igcse-cs',
    title: 'Cambridge IGCSE Computer Science 0478 (Year 10 Systems, Logic & Python)',
    shortTitle: 'Cambridge CS Year 10 (0478)',
    category: 'Cambridge International (Years 9-11)',
    tag: '💻 CAIE Year 10 CS 0478',
    tagColor: '#8b5cf6',
    duration: '12 Weeks (Syllabus Part 1)',
    durationWeeks: 12,
    schedule: 'Live Hands-On Coding & Exam Theory Labs',
    feeUsd: 85,
    feeKes: 11050,
    feeDisplay: '$85 / KES 11,050',
    originalFeeUsd: 170,
    discountBadge: '50% OFF',
    installmentText: '2 installments of $43 (KES 5,525)',
    instructor: 'Eng. Alex Mwangi • Senior Software Engineer & CS Instructor',
    schoolId: 'school-cambridge',
    schoolName: 'School of Cambridge International Curriculum (CAIE)',
    departmentId: 'dept-caie-math-cs',
    departmentName: 'Department of Cambridge Mathematical & Computational Sciences',
    yearLevel: 'Year 10',
    examBoard: 'Cambridge (CAIE)',
    syllabusCode: '0478',
    careerOutcome: 'Target Grade 9 / A* in CS 0478 • Direct Entry into High-School Software Projects & A-Level CS',
    skills: [
      'Data Representation & Logic Gates',
      'Computer Architecture & Fetch-Execute Cycle',
      'Networks, Cyber Security & Protocols',
      'Algorithms, Flowcharts & Pseudocode',
      'Python Programming for Paper 2',
      'Arrays, Validation & File Handling',
    ],
    icon: '💻',
    bestseller: true,
    popular: true,
    rating: 4.98,
    ratingCount: 640,
    studentsEnrolled: 1650,
    syllabus: [
      { week: 'Week 1-2', topic: 'Binary, Hexadecimal, ASCII/Unicode & Media Representation', practicalLab: 'Number base conversions and data storage size calculations.' },
      { week: 'Week 3-4', topic: 'Logic Gates (AND, OR, NOT, NAND, NOR, XOR) & Truth Tables', practicalLab: 'Designing logic circuits from problem statements.' },
      { week: 'Week 5-6', topic: 'CPU Architecture (Von Neumann), Operating Systems & Networks', practicalLab: 'Tracing the Fetch-Decode-Execute cycle and register operations.' },
      { week: 'Week 7-8', topic: 'Cyber Security, Encryption & Software Ethics', practicalLab: 'Symmetric/Asymmetric encryption analysis and security threats.' },
      { week: 'Week 9-10', topic: 'Paper 2: Algorithms, Flowcharts, Pseudocode & Trace Tables', practicalLab: 'Dry running trace tables with loops, 1D/2D arrays, and conditions.' },
      { week: 'Week 11-12', topic: 'Paper 2 15-Mark Scenario Problem & Full Mock Simulation', practicalLab: 'Writing complete Python programs for Cambridge Paper 2 scenario tasks.' },
    ],
  },
  {
    id: 'c-igcse-english',
    title: 'Cambridge IGCSE First Language English 0500 (Year 10 Reading & Directed Writing)',
    shortTitle: 'Cambridge English Year 10 (0500)',
    category: 'Cambridge International (Years 9-11)',
    tag: '✍️ CAIE Year 10 English 0500',
    tagColor: '#f59e0b',
    duration: '10 Weeks (Syllabus Part 1)',
    durationWeeks: 10,
    schedule: 'Live Interactive Essay Workshops & Text Critiques',
    feeUsd: 80,
    feeKes: 10400,
    feeDisplay: '$80 / KES 10,400',
    originalFeeUsd: 160,
    discountBadge: '50% OFF',
    installmentText: '2 installments of $40 (KES 5,200)',
    instructor: 'Mrs. Victoria Sinclair • Cambridge Senior Literature Faculty',
    schoolId: 'school-cambridge',
    schoolName: 'School of Cambridge International Curriculum (CAIE)',
    departmentId: 'dept-caie-languages',
    departmentName: 'Department of Cambridge Languages & World Literature',
    yearLevel: 'Year 10',
    examBoard: 'Cambridge (CAIE)',
    syllabusCode: '0500',
    careerOutcome: 'Target Grade 9 / A* • Essential Prerequisite for University Matriculation Globally',
    skills: [
      'Unseen Text Reading Comprehension',
      'Writer’s Effect & Figurative Analysis',
      'Directed Writing (Speeches, Articles, Letters)',
      'Descriptive & Narrative Composition',
      'Summary Writing Under Strict Word Limits',
      'High-Level Vocabulary & Rhetoric',
    ],
    icon: '📖',
    popular: true,
    rating: 4.91,
    ratingCount: 310,
    studentsEnrolled: 820,
    syllabus: [
      { week: 'Week 1-2', topic: 'Reading Comprehension & 15-Mark Extended Response to Reading', practicalLab: 'Text analysis and implicit vs explicit meaning dissection.' },
      { week: 'Week 3-4', topic: 'Writer’s Effect Question: Dissecting Imagery, Metaphor & Mood', practicalLab: 'Step-by-step scoring of 3-point explanation answers for Band 1 marks.' },
      { week: 'Week 5-6', topic: 'Summary Writing (Question 3): Extracting 10 Points in 120 Words', practicalLab: 'Timed summary drafting with strict concise paraphrase rules.' },
      { week: 'Week 7-8', topic: 'Paper 2 Directed Writing: Persuasive Articles, Letters & Speeches', practicalLab: 'Audience register matching, rhetoric devices, and counter-arguments.' },
      { week: 'Week 9-10', topic: 'Paper 2 Composition: Descriptive & Narrative Masterclasses', practicalLab: 'Full Paper 1 & Paper 2 timed mock marking under official rubrics.' },
    ],
  },
  {
    id: 'c-igcse-business',
    title: 'Cambridge IGCSE Business Studies 0450 (Year 10 Enterprise & Marketing)',
    shortTitle: 'Cambridge Business Year 10 (0450)',
    category: 'Cambridge International (Years 9-11)',
    tag: '💼 CAIE Year 10 Business 0450',
    tagColor: '#059669',
    duration: '10 Weeks (Syllabus Part 1)',
    durationWeeks: 10,
    schedule: 'Live Online Interactive Batches (May/June & Oct/Nov Series)',
    feeUsd: 80,
    feeKes: 10400,
    feeDisplay: '$80 / KES 10,400',
    originalFeeUsd: 160,
    discountBadge: '50% OFF',
    installmentText: '2 installments of $40 (KES 5,200)',
    instructor: 'Mr. David Ombasa • MBA, Cambridge Certified Business Instructor',
    schoolId: 'school-cambridge',
    schoolName: 'School of Cambridge International Curriculum (CAIE)',
    departmentId: 'dept-caie-business',
    departmentName: 'Department of Cambridge Humanities, Business & Social Sciences',
    yearLevel: 'Year 10',
    examBoard: 'Cambridge (CAIE)',
    syllabusCode: '0450',
    careerOutcome: 'Target Grade 9 / A* • Foundation for International Business, Economics & Management',
    skills: [
      'Business Activity & Classification',
      'People in Business & Motivation (Taylor/Maslow)',
      'Marketing Strategies & 4Ps',
      'Operations Management & Quality',
      'Financial Statements, Cash Flow & Ratios',
      'Paper 2 12-Mark Evaluative Justifications',
    ],
    icon: '📊',
    popular: true,
    rating: 4.88,
    ratingCount: 290,
    studentsEnrolled: 740,
    syllabus: [
      { week: 'Week 1-2', topic: 'Business Objectives, Enterprise & Stakeholders', practicalLab: 'Case study analysis of sole traders, partnerships, and multinational corps.' },
      { week: 'Week 3-4', topic: 'Human Resources: Motivation, Leadership Styles & Recruitment', practicalLab: 'Answering Paper 1 6-mark analysis questions on labor productivity.' },
      { week: 'Week 5-6', topic: 'Marketing: Market Research, Segmentation & Product Life Cycle', practicalLab: 'Formulating pricing strategies and marketing mix for new startups.' },
      { week: 'Week 7-8', topic: 'Operations: Production Methods, Economies of Scale & Lean', practicalLab: 'Break-even charts and lean manufacturing case studies.' },
      { week: 'Week 9-10', topic: 'Finance: Cash Flow Forecasts, Balance Sheets & Ratio Analysis', practicalLab: 'Full Paper 2 case study scenario with 12-mark recommendation questions.' },
    ],
  },

  // --- Cambridge Year 11 (IGCSE Year 2 Exam Prep & Past Paper Intensive) ---
  {
    id: 'c-caie-y11-math',
    title: 'Cambridge IGCSE Mathematics 0580 (Year 11 Paper 2 & 4 Past Paper Intensive)',
    shortTitle: 'Cambridge Math Year 11 Exam Series',
    category: 'Cambridge International (Years 9-11)',
    tag: '🎯 CAIE Year 11 Exam Series',
    tagColor: '#0284c7',
    duration: '10 Weeks (Final Mocks & Exam Series)',
    durationWeeks: 10,
    schedule: 'Past Paper Speed Marathons & Examiner Marking Schemes',
    feeUsd: 90,
    feeKes: 11700,
    feeDisplay: '$90 / KES 11,700',
    originalFeeUsd: 180,
    discountBadge: '50% OFF',
    installmentText: '2 installments of $45 (KES 5,850)',
    instructor: 'Dr. Michael Davies & Cambridge Senior Math Examiner Panel',
    schoolId: 'school-cambridge',
    schoolName: 'School of Cambridge International Curriculum (CAIE)',
    departmentId: 'dept-caie-math-cs',
    departmentName: 'Department of Cambridge Mathematical & Computational Sciences',
    yearLevel: 'Year 11',
    examBoard: 'Cambridge (CAIE)',
    syllabusCode: '0580',
    careerOutcome: 'Achieving Grade 9 / A* in 0580 • Guaranteed Mastery of Extended Paper 2 and Paper 4',
    skills: ['Paper 2 Non-Calculator Speed Tactics', 'Paper 4 Multi-Step Structured Solutions', 'Grade Boundary Optimization (2018-2025 Series)', 'Examiner Tricky Question Traps'],
    icon: '📐',
    bestseller: true,
    popular: true,
    rating: 4.99,
    ratingCount: 480,
    studentsEnrolled: 1250,
    syllabus: [
      { week: 'Week 1-2', topic: 'Paper 2 Speed Run: 2021-2023 May/June Series', practicalLab: 'Completing 70-mark paper within 90 minutes under strict timer.' },
      { week: 'Week 3-4', topic: 'Paper 4 Extended Calculus, Geometry & Functions Deep Dive', practicalLab: 'Step-by-step mark scheme dissection for 6-mark questions.' },
      { week: 'Week 5-6', topic: 'Circle Theorems, 3D Trigonometry & Vector Proof Traps', practicalLab: 'High-frequency challenging past paper question bank.' },
      { week: 'Week 7-8', topic: 'Probability Trees, Venn Diagrams & Cumulative Frequency', practicalLab: 'Graph accuracy and quartile calculation drills.' },
      { week: 'Week 9-10', topic: 'Full Official May/June Mock Exam Series Simulation', practicalLab: 'Individualized candidate grade boundary evaluation report.' },
    ],
  },
  {
    id: 'c-caie-y11-physics',
    title: 'Cambridge IGCSE Physics 0625 (Year 11 Paper 4 Theory & Paper 6 ATP Intensive)',
    shortTitle: 'Cambridge Physics Year 11 Exam Series',
    category: 'Cambridge International (Years 9-11)',
    tag: '⚡ CAIE Year 11 Exam Series',
    tagColor: '#6366f1',
    duration: '10 Weeks (Final Mocks & ATP)',
    durationWeeks: 10,
    schedule: 'Paper 4 Advanced Theory & Paper 6 Virtual Lab Practicals',
    feeUsd: 90,
    feeKes: 11700,
    feeDisplay: '$90 / KES 11,700',
    originalFeeUsd: 180,
    discountBadge: '50% OFF',
    installmentText: '2 installments of $45 (KES 5,850)',
    instructor: 'Eng. Sarah Jenkins • Oxford Cambridge Physics Specialist',
    schoolId: 'school-cambridge',
    schoolName: 'School of Cambridge International Curriculum (CAIE)',
    departmentId: 'dept-caie-sciences',
    departmentName: 'Department of Cambridge Natural & Experimental Sciences',
    yearLevel: 'Year 11',
    examBoard: 'Cambridge (CAIE)',
    syllabusCode: '0625',
    careerOutcome: 'Achieving Grade 9 / A* in 0625 • Seamless Foundation for Cambridge International A-Level Physics',
    skills: ['Paper 4 Extended Mechanics & Electromagnetism', 'Paper 6 Alternative to Practical Investigation Planning', 'Experimental Variables & Accuracy Limits', 'Past Papers 2019-2025 Series'],
    icon: '⚡',
    popular: true,
    rating: 4.97,
    ratingCount: 390,
    studentsEnrolled: 980,
    syllabus: [
      { week: 'Week 1-2', topic: 'Paper 4 High-Yield Calculation Traps (Momentum, Transformers, Latent Heat)', practicalLab: 'Formula manipulation and unit conversions under time pressure.' },
      { week: 'Week 3-4', topic: 'Electromagnetism, Transformers, Space Physics & Redshift', practicalLab: 'Doppler effect equations and cosmic microwave background analysis.' },
      { week: 'Week 5-6', topic: 'Paper 6: Planning an Investigation (7-Mark Scenario Questions)', practicalLab: 'Writing complete experimental procedure, variables, table, and safety.' },
      { week: 'Week 7-8', topic: 'Paper 6: Graphical Analysis, Best-Fit Lines & Gradient Calculation', practicalLab: 'Precise scale selection and error bar interpretation.' },
      { week: 'Week 9-10', topic: 'Full Timed Paper 2, Paper 4 & Paper 6 Mock Exam Series', practicalLab: 'Official marking session with examiner reports.' },
    ],
  },
  {
    id: 'c-caie-y11-cs',
    title: 'Cambridge IGCSE Computer Science 0478 (Year 11 Paper 1 & Paper 2 Scenario Masterclass)',
    shortTitle: 'Cambridge CS Year 11 Exam Series',
    category: 'Cambridge International (Years 9-11)',
    tag: '💻 CAIE Year 11 Exam Series',
    tagColor: '#8b5cf6',
    duration: '10 Weeks (Scenario Problem Solving)',
    durationWeeks: 10,
    schedule: 'Live Python Coding, Trace Tables & Past Paper Drills',
    feeUsd: 90,
    feeKes: 11700,
    feeDisplay: '$90 / KES 11,700',
    originalFeeUsd: 180,
    discountBadge: '50% OFF',
    installmentText: '2 installments of $45 (KES 5,850)',
    instructor: 'Eng. Alex Mwangi • Senior Software Engineer & CS Instructor',
    schoolId: 'school-cambridge',
    schoolName: 'School of Cambridge International Curriculum (CAIE)',
    departmentId: 'dept-caie-math-cs',
    departmentName: 'Department of Cambridge Mathematical & Computational Sciences',
    yearLevel: 'Year 11',
    examBoard: 'Cambridge (CAIE)',
    syllabusCode: '0478',
    careerOutcome: 'Achieving Grade 9 / A* in CS 0478 • Direct Preparation for Cambridge International A-Level CS 9618',
    skills: ['Paper 2 15-Mark Problem Solving Mastery', 'Writing Flawless Python & Pseudocode', '2D Arrays, File Handling & Validation', 'Paper 1 Theory High-Frequency Past Papers'],
    icon: '💻',
    bestseller: true,
    popular: true,
    rating: 4.99,
    ratingCount: 510,
    studentsEnrolled: 1380,
    syllabus: [
      { week: 'Week 1-2', topic: 'Paper 1 Theory Sprint: 2021-2024 Past Paper Series', practicalLab: 'Memory registers, interrupt handlers, and network topology questions.' },
      { week: 'Week 3-4', topic: 'Pseudocode Syntax Standards & Trace Table Zero-Error Drills', practicalLab: 'Dry running complex nested loops and array indexing.' },
      { week: 'Week 5-6', topic: 'Paper 2 Section B 15-Mark Unseen Scenario Deconstruction', practicalLab: 'Writing robust Python solutions with input validation and formatting.' },
      { week: 'Week 7-8', topic: 'File Reading/Writing, Boolean Logic Simplification & SQL Select', practicalLab: 'Writing SQL SELECT queries and logic gate algebraic statements.' },
      { week: 'Week 9-10', topic: 'Full Official Cambridge Paper 1 & Paper 2 Mock Marathon', practicalLab: 'Live examiner critique and individual code review.' },
    ],
  },

  // ============================================================
  // SCHOOL OF PEARSON EDEXCEL INTERNATIONAL CURRICULUM
  // Years 9 (iLowerSecondary), 10 (iGCSE Year 1), 11 (Exam Prep)
  // ============================================================

  // --- Pearson Edexcel Year 9 (iLowerSecondary Foundation) ---
  {
    id: 'c-edx-y9-math',
    title: 'Pearson Edexcel iLowerSecondary Mathematics (Year 9 Foundation)',
    shortTitle: 'Edexcel Math Year 9 (Foundation)',
    category: 'Pearson Edexcel International (Years 9-11)',
    tag: '🇬🇧 Edexcel Year 9 Foundation',
    tagColor: '#dc2626',
    duration: '10 Weeks (Foundation Year)',
    durationWeeks: 10,
    schedule: 'Live Online Interactive Batches (Modular iLowerSecondary)',
    feeUsd: 75,
    feeKes: 9750,
    feeDisplay: '$75 / KES 9,750',
    originalFeeUsd: 150,
    discountBadge: '50% OFF',
    installmentText: '2 installments of $38 (KES 4,875)',
    instructor: 'Prof. Alistair Sterling • London Edexcel Specialist',
    schoolId: 'school-edexcel',
    schoolName: 'School of Pearson Edexcel International Curriculum',
    departmentId: 'dept-edx-stem',
    departmentName: 'Department of Edexcel STEM & Pure Sciences',
    yearLevel: 'Year 9',
    examBoard: 'Pearson Edexcel',
    careerOutcome: 'iLowerSecondary Award Distinction • Direct Preparation for Edexcel International GCSE 4MA1',
    skills: ['Numerical Fluency & Estimation', 'Algebraic Factorization & Formulas', 'Angles, Polygons & Circle Geometry', 'Ratio, Proportion & Financial Math'],
    icon: '📐',
    popular: true,
    rating: 4.92,
    ratingCount: 260,
    studentsEnrolled: 620,
    syllabus: [
      { week: 'Week 1-2', topic: 'Integers, Powers, Roots & Standard Index Form', practicalLab: 'Calculator speed and precision drills.' },
      { week: 'Week 3-4', topic: 'Expanding Brackets, Factorizing & Linear Graphs', practicalLab: 'Graph plotting on Cartesian coordinate grids.' },
      { week: 'Week 5-6', topic: 'Percentages, Compound Interest & Foreign Currency Exchange', practicalLab: 'Real-world financial arithmetic problem sheets.' },
      { week: 'Week 7-8', topic: 'Perimeter, Area & Volume of Compound Shapes', practicalLab: 'Compound 3D composite volume calculations.' },
      { week: 'Week 9-10', topic: 'Pearson Edexcel iLowerSecondary Mock Examination', practicalLab: 'Complete past examination evaluation.' },
    ],
  },
  {
    id: 'c-edx-y9-science',
    title: 'Pearson Edexcel iLowerSecondary Science (Year 9 Foundation)',
    shortTitle: 'Edexcel Science Year 9 (Foundation)',
    category: 'Pearson Edexcel International (Years 9-11)',
    tag: '🔬 Edexcel Year 9 Science',
    tagColor: '#ea580c',
    duration: '10 Weeks (Foundation Year)',
    durationWeeks: 10,
    schedule: 'Live Online Lecture & Virtual Laboratory Simulations',
    feeUsd: 75,
    feeKes: 9750,
    feeDisplay: '$75 / KES 9,750',
    originalFeeUsd: 150,
    discountBadge: '50% OFF',
    installmentText: '2 installments of $38 (KES 4,875)',
    instructor: 'Dr. Evelyn Dubois & Faculty Panel',
    schoolId: 'school-edexcel',
    schoolName: 'School of Pearson Edexcel International Curriculum',
    departmentId: 'dept-edx-stem',
    departmentName: 'Department of Edexcel STEM & Pure Sciences',
    yearLevel: 'Year 9',
    examBoard: 'Pearson Edexcel',
    careerOutcome: 'iLowerSecondary Science Attainment • Bridge into Edexcel International GCSE Triple Science',
    skills: ['Energy Resources & Circuits', 'Chemical Reactions & States of Matter', 'Cells, Genetics & Ecosystems', 'Scientific Enquiry & Lab Planning'],
    icon: '🔬',
    popular: true,
    rating: 4.91,
    ratingCount: 220,
    studentsEnrolled: 540,
    syllabus: [
      { week: 'Week 1-2', topic: 'Cells, Organ Systems & Microscope Observations', practicalLab: 'Virtual microscope cell staining and magnification calculations.' },
      { week: 'Week 3-4', topic: 'Elements, Mixtures & Separation Techniques (Chromatography, Distillation)', practicalLab: 'Virtual chromatography Rf value determinations.' },
      { week: 'Week 5-6', topic: 'Energy Transfers, Work Done & Power Calculations', practicalLab: 'Work and power problem sets.' },
      { week: 'Week 7-8', topic: 'Light & Sound Waves, Reflection & Refraction', practicalLab: 'Ray optics virtual simulations.' },
      { week: 'Week 9-10', topic: 'Pearson Edexcel iLowerSecondary Science Mock', practicalLab: 'Full timed assessment and question dissection.' },
    ],
  },

  // --- Pearson Edexcel Year 10 (International GCSE Year 1 - 9-1 Linear) ---
  {
    id: 'c-edx-y10-math',
    title: 'Pearson Edexcel International GCSE (9-1) Mathematics A 4MA1 (Year 10 Higher Tier)',
    shortTitle: 'Edexcel Math Year 10 (4MA1)',
    category: 'Pearson Edexcel International (Years 9-11)',
    tag: '🇬🇧 Edexcel Year 10 Math 4MA1',
    tagColor: '#dc2626',
    duration: '12 Weeks (Syllabus Part 1)',
    durationWeeks: 12,
    schedule: 'Live Interactive Lectures (Higher Tier 9-1 Focus)',
    feeUsd: 85,
    feeKes: 11050,
    feeDisplay: '$85 / KES 11,050',
    originalFeeUsd: 170,
    discountBadge: '50% OFF',
    installmentText: '2 installments of $43 (KES 5,525)',
    instructor: 'Prof. Alistair Sterling • London Edexcel Specialist',
    schoolId: 'school-edexcel',
    schoolName: 'School of Pearson Edexcel International Curriculum',
    departmentId: 'dept-edx-stem',
    departmentName: 'Department of Edexcel STEM & Pure Sciences',
    yearLevel: 'Year 10',
    examBoard: 'Pearson Edexcel',
    syllabusCode: '4MA1',
    careerOutcome: 'Target Grade 9 in Edexcel 4MA1 • Gateway to A-Level Further Math, Engineering & Finance',
    skills: ['Surds, Indices & Algebraic Fractions', 'Quadratic Inequalities & Turning Points', 'Trigonometric Ratios & 3D Vectors', 'Histograms & Cumulative Frequency', 'Paper 1H Question Traps'],
    icon: '📐',
    bestseller: true,
    popular: true,
    rating: 4.97,
    ratingCount: 430,
    studentsEnrolled: 1050,
    syllabus: [
      { week: 'Week 1-2', topic: 'Surds Rationalization, Fractional Indices & Set Theory Venn Diagrams', practicalLab: 'Rigorous algebraic proof and surd simplification.' },
      { week: 'Week 3-4', topic: 'Completing the Square, Quadratic Formula & Non-Linear Simultaneous Equations', practicalLab: 'Intersection of line and circle problem sets.' },
      { week: 'Week 5-6', topic: 'Functions (Composite, Inverse, Domain/Range) & Graph Transformations', practicalLab: 'f(x+a) and af(x) geometric transformations.' },
      { week: 'Week 7-8', topic: 'Sine & Cosine Rules, 3D Pythagoras & Bearings', practicalLab: 'Calculating angles of elevation in complex 3D triangular prisms.' },
      { week: 'Week 9-10', topic: 'Vectors Proofs & Matrix Multiplications', practicalLab: 'Geometric proofs of collinearity and parallel vectors.' },
      { week: 'Week 11-12', topic: 'Probability Trees, Conditional Probability & Mock 1H Assessment', practicalLab: 'Full timed 100-mark Paper 1H simulation.' },
    ],
  },
  {
    id: 'c-edx-y10-physics',
    title: 'Pearson Edexcel International GCSE (9-1) Physics 4PH1 (Year 10 Principles)',
    shortTitle: 'Edexcel Physics Year 10 (4PH1)',
    category: 'Pearson Edexcel International (Years 9-11)',
    tag: '⚡ Edexcel Year 10 Physics 4PH1',
    tagColor: '#6366f1',
    duration: '12 Weeks (Syllabus Part 1)',
    durationWeeks: 12,
    schedule: 'Live Online Lecture & Practical Investigation Labs',
    feeUsd: 85,
    feeKes: 11050,
    feeDisplay: '$85 / KES 11,050',
    originalFeeUsd: 170,
    discountBadge: '50% OFF',
    installmentText: '2 installments of $43 (KES 5,525)',
    instructor: 'Dr. Marcus Vance • Edexcel Senior Science Faculty',
    schoolId: 'school-edexcel',
    schoolName: 'School of Pearson Edexcel International Curriculum',
    departmentId: 'dept-edx-stem',
    departmentName: 'Department of Edexcel STEM & Pure Sciences',
    yearLevel: 'Year 10',
    examBoard: 'Pearson Edexcel',
    syllabusCode: '4PH1',
    careerOutcome: 'Target Grade 9 in Edexcel 4PH1 • Pathway into International A-Level Physics & Engineering',
    skills: ['Forces & Motion, Terminal Velocity', 'Mains Electricity, Resistance & Power', 'Waves, Refraction & Total Internal Reflection', 'Energy Resources & Efficiency Calculations'],
    icon: '⚡',
    popular: true,
    rating: 4.95,
    ratingCount: 360,
    studentsEnrolled: 820,
    syllabus: [
      { week: 'Week 1-2', topic: 'Equations of Motion (v=u+at, s=ut+0.5at2), Friction & Terminal Velocity', practicalLab: 'Ticker tape and light gate velocity calculation drills.' },
      { week: 'Week 3-4', topic: 'Hooke’s Law, Elasticity, Momentum & Car Safety (Crumple Zones)', practicalLab: 'Momentum conservation calculations in inelastic collisions.' },
      { week: 'Week 5-6', topic: 'Mains Electricity, AC vs DC, Fuses, Earthing & Electrical Power', practicalLab: 'Circuit wiring and electrical safety case studies.' },
      { week: 'Week 7-8', topic: 'Electromagnetic Spectrum, Critical Angle & Optical Fibres', practicalLab: 'Snell’s law calculations and refractive index lab sheets.' },
      { week: 'Week 9-10', topic: 'Thermal Energy, Specific Heat Capacity & Convection Currents', practicalLab: 'Virtual calorific experiment simulations.' },
      { week: 'Week 11-12', topic: 'Paper 1P Mid-Course Mock Examination & Detailed Feedback', practicalLab: 'Full Paper 1P past exam marking.' },
    ],
  },
  {
    id: 'c-edx-y10-cs',
    title: 'Pearson Edexcel International GCSE (9-1) Computer Science 4CP0 (Year 10 Algorithms & Python)',
    shortTitle: 'Edexcel CS Year 10 (4CP0)',
    category: 'Pearson Edexcel International (Years 9-11)',
    tag: '💻 Edexcel Year 10 CS 4CP0',
    tagColor: '#8b5cf6',
    duration: '12 Weeks (Theory & Python)',
    durationWeeks: 12,
    schedule: 'Interactive Coding Labs (Paper 1 Theory & Paper 2 Onscreen)',
    feeUsd: 85,
    feeKes: 11050,
    feeDisplay: '$85 / KES 11,050',
    originalFeeUsd: 170,
    discountBadge: '50% OFF',
    installmentText: '2 installments of $43 (KES 5,525)',
    instructor: 'Eng. Marcus Thorne • Edexcel Computing Specialist',
    schoolId: 'school-edexcel',
    schoolName: 'School of Pearson Edexcel International Curriculum',
    departmentId: 'dept-edx-digital',
    departmentName: 'Department of Edexcel Digital Technologies & Computer Science',
    yearLevel: 'Year 10',
    examBoard: 'Pearson Edexcel',
    syllabusCode: '4CP0',
    careerOutcome: 'Target Grade 9 in Edexcel 4CP0 • Preparation for Onscreen Python Programming Exam',
    skills: ['Computational Thinking & Searching Algorithms', 'Data Types & Representation', 'Python Programming (Paper 2 Onscreen Focus)', 'Hardware, Software & Networks'],
    icon: '💻',
    popular: true,
    rating: 4.96,
    ratingCount: 340,
    studentsEnrolled: 790,
    syllabus: [
      { week: 'Week 1-2', topic: 'Decomposition, Pattern Recognition & Binary/Linear Search', practicalLab: 'Tracing search algorithms and sorting arrays.' },
      { week: 'Week 3-4', topic: 'Data Representation (Images, Sound, Characters & Compression)', practicalLab: 'Image file size and sound sampling rate calculations.' },
      { week: 'Week 5-6', topic: 'Paper 2 Onscreen Python: Functions, Subroutines & Parameter Passing', practicalLab: 'Coding modular Python functions with local/global scope.' },
      { week: 'Week 7-8', topic: 'Text File I/O, Exception Handling & Data Validation in Python', practicalLab: 'Writing robust file read/write scripts for student records.' },
      { week: 'Week 9-10', topic: 'Computer Networks, Topologies, Protocols & Network Security', practicalLab: 'Analyzing packet switching and TCP/IP layers.' },
      { week: 'Week 11-12', topic: 'Paper 1 Theory & Paper 2 Onscreen Python Mock Exam', practicalLab: 'Timed onscreen coding assessment with automated test runner.' },
    ],
  },
  {
    id: 'c-edx-y10-business',
    title: 'Pearson Edexcel International GCSE (9-1) Business 4BS1 & Economics 4EC1 (Year 10)',
    shortTitle: 'Edexcel Business Year 10 (4BS1)',
    category: 'Pearson Edexcel International (Years 9-11)',
    tag: '💼 Edexcel Year 10 Business 4BS1',
    tagColor: '#059669',
    duration: '10 Weeks (Commerce Core)',
    durationWeeks: 10,
    schedule: 'Live Interactive Business Case Study Analysis',
    feeUsd: 80,
    feeKes: 10400,
    feeDisplay: '$80 / KES 10,400',
    originalFeeUsd: 160,
    discountBadge: '50% OFF',
    installmentText: '2 installments of $40 (KES 5,200)',
    instructor: 'Mrs. Fiona Campbell, M.Sc. • Edexcel Business Panel',
    schoolId: 'school-edexcel',
    schoolName: 'School of Pearson Edexcel International Curriculum',
    departmentId: 'dept-edx-commerce',
    departmentName: 'Department of Edexcel Commerce, Finance & Global Economics',
    yearLevel: 'Year 10',
    examBoard: 'Pearson Edexcel',
    syllabusCode: '4BS1',
    careerOutcome: 'Target Grade 9 in Edexcel 4BS1 • Foundation for Global Commerce & Finance',
    skills: ['Business Activity & Influences', 'People in Business & Organization Structures', 'Marketing & Sales Mix', 'Operations Management & Quality Control'],
    icon: '💼',
    popular: true,
    rating: 4.89,
    ratingCount: 270,
    studentsEnrolled: 680,
    syllabus: [
      { week: 'Week 1-2', topic: 'Business Activity, Growth (Mergers/Takeovers) & Objectives', practicalLab: 'Analyzing corporate diversification case studies.' },
      { week: 'Week 3-4', topic: 'Recruitment, Training, Employee Motivation & Appraisal', practicalLab: 'Writing 6-mark analysis answers on organizational motivation.' },
      { week: 'Week 5-6', topic: 'Market Research, The Marketing Mix & E-Commerce Expansion', practicalLab: 'Designing market entry strategies for international firms.' },
      { week: 'Week 7-8', topic: 'Production Methods (Job, Batch, Flow) & Quality Assurance', practicalLab: 'Supply chain management and just-in-time (JIT) calculations.' },
      { week: 'Week 9-10', topic: 'Edexcel Paper 1 Investigating Small Businesses Mock', practicalLab: '12-mark evaluation question technique workshop.' },
    ],
  },

  // --- Pearson Edexcel Year 11 (International GCSE Year 2 Exam Prep & Past Papers) ---
  {
    id: 'c-edx-y11-math',
    title: 'Pearson Edexcel International GCSE Math 4MA1 (Year 11 Paper 1H & 2H Past Papers)',
    shortTitle: 'Edexcel Math Year 11 Exam Series',
    category: 'Pearson Edexcel International (Years 9-11)',
    tag: '🎯 Edexcel Year 11 Exam Series',
    tagColor: '#dc2626',
    duration: '10 Weeks (Final Mocks & Exam Series)',
    durationWeeks: 10,
    schedule: 'Paper 1H & 2H Past Paper Marathons (2018-2025 Series)',
    feeUsd: 90,
    feeKes: 11700,
    feeDisplay: '$90 / KES 11,700',
    originalFeeUsd: 180,
    discountBadge: '50% OFF',
    installmentText: '2 installments of $45 (KES 5,850)',
    instructor: 'Prof. Alistair Sterling • London Edexcel Specialist',
    schoolId: 'school-edexcel',
    schoolName: 'School of Pearson Edexcel International Curriculum',
    departmentId: 'dept-edx-stem',
    departmentName: 'Department of Edexcel STEM & Pure Sciences',
    yearLevel: 'Year 11',
    examBoard: 'Pearson Edexcel',
    syllabusCode: '4MA1',
    careerOutcome: 'Target Grade 9 in Edexcel 4MA1 Higher Tier • Perfect Preparation for Edexcel IAL Math',
    skills: ['Paper 1H & 2H Higher Tier Examination Tactics', 'Non-Calculator & Calculator Precision', 'Calculus Differentiation & Maxima/Minima', 'Histograms & Probability Proofs'],
    icon: '📐',
    bestseller: true,
    popular: true,
    rating: 4.98,
    ratingCount: 420,
    studentsEnrolled: 1120,
    syllabus: [
      { week: 'Week 1-2', topic: 'Paper 1H Sprint: 2021-2023 Series Question Traps', practicalLab: 'Timed 2-hour paper completion under official conditions.' },
      { week: 'Week 3-4', topic: 'Differentiation, Turning Points, Gradients & Kinematics', practicalLab: 'Solving multi-step calculus rate-of-change questions.' },
      { week: 'Week 5-6', topic: 'Geometric Vector Proofs & Similar Area/Volume Scale Factors', practicalLab: 'Dissecting 5-mark geometric proof problems.' },
      { week: 'Week 7-8', topic: 'Paper 2H Sprint: Conditional Probability & Algebraic Fractions', practicalLab: 'Algebraic fraction simplification under timer.' },
      { week: 'Week 9-10', topic: 'Full Official Edexcel 1H & 2H Mock Examination Marathon', practicalLab: 'Detailed candidate boundary ranking and score report.' },
    ],
  },
  {
    id: 'c-edx-y11-physics',
    title: 'Pearson Edexcel International GCSE Physics 4PH1 (Year 11 Paper 1P & 2P Exam Series)',
    shortTitle: 'Edexcel Physics Year 11 Exam Series',
    category: 'Pearson Edexcel International (Years 9-11)',
    tag: '⚡ Edexcel Year 11 Exam Series',
    tagColor: '#6366f1',
    duration: '10 Weeks (Paper 1P & 2P Mastery)',
    durationWeeks: 10,
    schedule: 'Paper 1P Core & Paper 2P Extension Problem Sessions',
    feeUsd: 90,
    feeKes: 11700,
    feeDisplay: '$90 / KES 11,700',
    originalFeeUsd: 180,
    discountBadge: '50% OFF',
    installmentText: '2 installments of $45 (KES 5,850)',
    instructor: 'Dr. Marcus Vance • Edexcel Senior Science Faculty',
    schoolId: 'school-edexcel',
    schoolName: 'School of Pearson Edexcel International Curriculum',
    departmentId: 'dept-edx-stem',
    departmentName: 'Department of Edexcel STEM & Pure Sciences',
    yearLevel: 'Year 11',
    examBoard: 'Pearson Edexcel',
    syllabusCode: '4PH1',
    careerOutcome: 'Target Grade 9 in Edexcel 4PH1 • Seamless Foundation for International A-Level Physics',
    skills: ['Paper 1P & 2P Mark Scheme Dissection', 'Radioactivity, Half-Life & Nuclear Fission/Fusion', 'Magnetism, Left-Hand Rule & Motor Effect', 'Astrophysics & Hertzsprung-Russell Diagram'],
    icon: '⚡',
    popular: true,
    rating: 4.96,
    ratingCount: 350,
    studentsEnrolled: 890,
    syllabus: [
      { week: 'Week 1-2', topic: 'Paper 1P High-Yield Topics: Mechanics & Waves Past Papers', practicalLab: 'Calculating acceleration, braking distance, and wave equations.' },
      { week: 'Week 3-4', topic: 'Nuclear Physics: Alpha/Beta Decay Equations & Reactor Control', practicalLab: 'Nuclear equations and chain reaction control analysis.' },
      { week: 'Week 5-6', topic: 'Paper 2P Extension: Motor Effect, Induction & Transformers', practicalLab: 'Applying Fleming’s Left-Hand Rule and generator principles.' },
      { week: 'Week 7-8', topic: 'Astrophysics: Stellar Evolution, H-R Diagrams & Big Bang Evidence', practicalLab: 'Doppler effect equations and cosmic microwave background analysis.' },
      { week: 'Week 9-10', topic: 'Full Official Edexcel 1P & 2P Mock Exam Simulation', practicalLab: 'Examiner grading and feedback on extended response questions.' },
    ],
  },
]

export function calculateDynamicFeeFields(feeUsd: number, originalBaseUsd?: number) {
  const safeUsd = Math.max(1, Number(feeUsd) || 60)
  const feeKes = Math.round(safeUsd * 130)
  const feeDisplay = `$${safeUsd} / KES ${feeKes.toLocaleString()}`
  const originalFeeUsd = originalBaseUsd && originalBaseUsd > safeUsd ? originalBaseUsd : Math.round(safeUsd * 2)
  const discountBadge = '50% OFF'
  const installmentText = safeUsd <= 55
    ? `Single payment of $${safeUsd} (KES ${feeKes.toLocaleString()})`
    : `2 installments of $${Math.ceil(safeUsd / 2)} (KES ${Math.ceil(feeKes / 2).toLocaleString()})`
  return { feeUsd: safeUsd, feeKes, feeDisplay, originalFeeUsd, discountBadge, installmentText }
}

export function getDynamicCoursesList(
  storeSubjects: Array<{ id: string; code: string; name: string; fee?: number; duration?: string; description?: string; category?: string; icon?: string; badge?: string; careers?: string[]; color_hex?: string; department_id?: string; department_name?: string }> = [],
  storeUnits: Array<{ id: string; code: string; title: string; fee?: number; course_duration?: string; description?: string; department?: string; program?: string; teacher_name?: string; live_schedule_text?: string; syllabus_modules?: any[] }> = [],
  customFees?: Record<string, number>
): CourseProgram[] {
  const activeCustomFees = customFees || (typeof window !== 'undefined' ? (() => {
    try {
      const stored = localStorage.getItem('eclat_school_custom_course_fees')
      return stored ? JSON.parse(stored) : {}
    } catch {
      return {}
    }
  })() : {})

  const safeStoreSubjects = (storeSubjects || []).filter(
    (s) =>
      s &&
      typeof s.id === 'string' &&
      !s.id.startsWith('aaaaaaaa-') &&
      !s.id.startsWith('__ECLAT_') &&
      !s.name?.startsWith('__ECLAT_') &&
      !s.name?.includes('SYNC') &&
      !s.description?.startsWith('{"key":') &&
      !s.description?.startsWith('{')
  )

  const safeStoreUnits = (storeUnits || []).filter(
    (u) =>
      u &&
      typeof u.id === 'string' &&
      !u.id.startsWith('aaaaaaaa-') &&
      !u.id.startsWith('__ECLAT_') &&
      !u.title?.startsWith('__ECLAT_') &&
      !u.title?.includes('SYNC') &&
      !u.description?.startsWith('{"key":') &&
      !u.description?.startsWith('{')
  )

  const programs: CourseProgram[] = []
  const usedSubjectIds = new Set<string>()
  const usedUnitIds = new Set<string>()

  for (const base of OFFICIAL_COURSES) {
    const matchedSub = safeStoreSubjects.find((s) => {
      if (s.id === base.id || s.id === `sub-${base.id.replace(/^c-/, '')}`) return true
      if (s.code && (s.code.toLowerCase() === base.id.toLowerCase() || s.code.toLowerCase() === base.shortTitle.toLowerCase())) return true
      const baseClean = base.shortTitle.toLowerCase().replace(/[^a-z0-9]/g, '')
      const subClean = s.name.toLowerCase().replace(/[^a-z0-9]/g, '')
      return baseClean.includes(subClean) || subClean.includes(baseClean)
    })
    if (matchedSub) usedSubjectIds.add(matchedSub.id)

    const matchedUnit = safeStoreUnits.find((u) => {
      if (u.id === base.id) return true
      if (u.code && (u.code.toLowerCase() === base.id.toLowerCase() || u.code.toLowerCase() === base.shortTitle.toLowerCase())) return true
      const baseClean = base.shortTitle.toLowerCase().replace(/[^a-z0-9]/g, '')
      const unitClean = u.title.toLowerCase().replace(/[^a-z0-9]/g, '')
      return baseClean.includes(unitClean) || unitClean.includes(baseClean)
    })
    if (matchedUnit) usedUnitIds.add(matchedUnit.id)

    const customOverrideFee = activeCustomFees?.[base.id] ?? (matchedSub?.id ? activeCustomFees?.[matchedSub.id] : undefined) ?? (matchedUnit?.id ? activeCustomFees?.[matchedUnit.id] : undefined)

    const liveFeeUsd = (typeof customOverrideFee === 'number' && customOverrideFee >= 0)
      ? customOverrideFee
      : (typeof matchedSub?.fee === 'number' && matchedSub.fee > 0)
      ? matchedSub.fee
      : (typeof matchedUnit?.fee === 'number' && matchedUnit.fee > 0)
      ? matchedUnit.fee
      : base.feeUsd

    const feeCalculations = calculateDynamicFeeFields(liveFeeUsd, base.originalFeeUsd)

    programs.push({
      ...base,
      ...feeCalculations,
      title: matchedSub?.name || matchedUnit?.title || base.title,
      duration: matchedSub?.duration || matchedUnit?.course_duration || base.duration,
      careerOutcome: (matchedSub?.description && !matchedSub.description.startsWith('{')) ? matchedSub.description : base.careerOutcome,
      skills: matchedSub?.careers && matchedSub.careers.length > 0 ? matchedSub.careers : base.skills,
    })
  }

  // Also append custom subjects created by admin
  for (const sub of safeStoreSubjects) {
    if (usedSubjectIds.has(sub.id)) continue
    const customOverrideFee = activeCustomFees?.[sub.id]
    const feeUsd = (typeof customOverrideFee === 'number' && customOverrideFee >= 0)
      ? customOverrideFee
      : typeof sub.fee === 'number' && sub.fee > 0 ? sub.fee : 60
    const feeCalculations = calculateDynamicFeeFields(feeUsd)
    programs.push({
      id: sub.id,
      title: sub.name,
      shortTitle: sub.name,
      category: (sub.category as any) || 'Tech & Programming',
      tag: `🏛️ ${sub.department_name || 'Academic Program'}`,
      tagColor: sub.color_hex || '#0f172a',
      duration: sub.duration || '3 Months Certificate',
      durationWeeks: 12,
      schedule: 'All Shifts: Early Morning, Late Morning, Midday, Afternoon, Evening & Night',
      ...feeCalculations,
      instructor: 'Éclat Institute Certified Faculty',
      departmentId: sub.department_id || 'dept-general',
      departmentName: sub.department_name || 'Academic Faculty',
      careerOutcome: (sub.description && !sub.description.startsWith('{')) ? sub.description : `${sub.name} Certified Specialist`,
      skills: sub.careers || ['Live Virtual Classes', 'Verified E-Certificate'],
      icon: sub.icon || '💻',
      popular: true,
      rating: 4.9,
      ratingCount: 120,
      studentsEnrolled: 450,
      syllabus: [
        { week: 'Module 1-2', topic: 'Foundations & Interactive Practice', practicalLab: 'Live virtual classroom lab and tools setup.' },
        { week: 'Module 3-4', topic: 'Capstone Lab & Evaluation', practicalLab: 'Online evaluation and certification project.' },
      ],
    })
  }

  // Also append custom course units created by faculty
  for (const unit of safeStoreUnits) {
    if (usedUnitIds.has(unit.id)) continue
    const customOverrideFee = activeCustomFees?.[unit.id]
    const feeUsd = (typeof customOverrideFee === 'number' && customOverrideFee >= 0)
      ? customOverrideFee
      : typeof unit.fee === 'number' && unit.fee > 0 ? unit.fee : 60
    const feeCalculations = calculateDynamicFeeFields(feeUsd)
    programs.push({
      id: unit.id,
      title: unit.title,
      shortTitle: unit.title,
      category: 'Tech & Programming',
      tag: `🏛️ ${unit.program || unit.department || 'Online Course'}`,
      tagColor: '#0f172a',
      duration: unit.course_duration || '3 Months Certificate',
      durationWeeks: 12,
      schedule: unit.live_schedule_text || 'All Shifts: Early Morning, Late Morning, Midday, Afternoon, Evening & Night',
      ...feeCalculations,
      instructor: unit.teacher_name || 'Éclat Faculty Specialist',
      departmentId: 'dept-curriculum',
      departmentName: unit.department || 'Department of Technology',
      careerOutcome: (unit.description && !unit.description.startsWith('{')) ? unit.description : 'Certified Online Graduate',
      skills: unit.syllabus_modules?.flatMap((m) => m.topics) || ['Live Interactive Virtual Classes', 'Verified E-Certificate'],
      icon: '🎨',
      popular: true,
      rating: 4.9,
      ratingCount: 85,
      studentsEnrolled: 320,
      syllabus: unit.syllabus_modules?.map((m, idx) => ({
        week: `Week ${idx + 1}`,
        topic: m.title,
        practicalLab: m.learning_outcomes?.[0] || 'Live online hands-on exercises and project labs.',
      })) || [],
    })
  }

  return programs
}

export function getOfficialCourseById(id: string, storeSubjects?: any[], storeUnits?: any[]): CourseProgram | undefined {
  const list = storeSubjects || storeUnits ? getDynamicCoursesList(storeSubjects, storeUnits) : OFFICIAL_COURSES
  return list.find((c) => c.id === id || c.shortTitle.toLowerCase().includes(id.toLowerCase()))
}

export function getOfficialCourseByTitle(title: string, storeSubjects?: any[], storeUnits?: any[]): CourseProgram | undefined {
  const list = storeSubjects || storeUnits ? getDynamicCoursesList(storeSubjects, storeUnits) : OFFICIAL_COURSES
  return list.find((c) => c.title.toLowerCase() === title.toLowerCase() || title.toLowerCase().includes(c.shortTitle.toLowerCase()))
}

