"""
strategies/base_strategy.py
============================
Abstract Base Strategy Interface.

ALL concrete strategies (trend_following, mean_reversion, breakout)
MUST subclass BaseStrategy and implement generate_signal().

The strategy is a PURE SIGNAL GENERATOR. It:
  ✅ Reads OHLCV data and technical indicators
  ✅ Returns a structured TradeSignal (direction + stop + target)
  ✅ Contains strategy-specific parameters

The strategy does NOT:
  ❌ Place orders directly
  ❌ Check risk limits or account balance
  ❌ Know about the broker or exchange
  ❌ Manage position sizing

All of those responsibilities belong to the risk manager, trade authorizer,
and order manager respectively. The strategy's ONLY job is to find edge.
"""

from __future__ import annotations

import abc
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Optional

import pandas as pd


# ---------------------------------------------------------------------------
# Signal Direction
# ---------------------------------------------------------------------------

class SignalDirection(str, Enum):
    LONG  = "long"    # Buy / go long
    SHORT = "short"   # Sell / go short
    FLAT  = "flat"    # No trade / close existing position
    HOLD  = "hold"    # Keep existing position, no action


# ---------------------------------------------------------------------------
# Trade Signal
# ---------------------------------------------------------------------------

@dataclass
class TradeSignal:
    """
    A trade recommendation generated by a strategy.

    The risk manager reads this signal and applies:
    - Position sizing (converts signal into actual quantity)
    - Final stop-loss price (based on ATR, not just strategy suggestion)
    - Portfolio-level risk gate (checks daily loss limits etc.)

    Before routing to the order manager.
    """
    # Core signal
    symbol:         str
    direction:      SignalDirection
    strategy_id:    str

    # Suggested price levels (risk manager may override based on ATR)
    entry_price:    Optional[float] = None    # None = market order
    stop_loss:      Optional[float] = None    # Structural stop suggestion
    take_profit:    Optional[float] = None    # Structural target suggestion

    # Signal quality metrics (used by ensemble weighting)
    confidence:     float = 1.0              # 0.0 to 1.0 (strategy's self-assessment)
    risk_reward:    Optional[float] = None   # Suggested RRR (e.g. 2.0 = 1:2 risk/reward)

    # Metadata
    timeframe:      str = "15m"
    generated_at:   datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    regime_context: Optional[str] = None    # Regime state when signal was generated
    notes:          str = ""

    def is_actionable(self) -> bool:
        """
        Returns True if this signal should trigger an order.
        FLAT and HOLD signals are not actionable (no new orders).
        """
        return self.direction in (SignalDirection.LONG, SignalDirection.SHORT)

    def implied_rrr(self) -> Optional[float]:
        """
        Compute the implied Risk-to-Reward Ratio from entry/stop/target.
        Returns None if any of the three prices are missing.
        """
        if not all([self.entry_price, self.stop_loss, self.take_profit]):
            return None
        risk   = abs(self.entry_price - self.stop_loss)
        reward = abs(self.take_profit - self.entry_price)
        if risk == 0:
            return None
        return reward / risk

    def __repr__(self) -> str:
        return (
            f"TradeSignal({self.direction.value.upper()} {self.symbol} | "
            f"strategy={self.strategy_id} | "
            f"confidence={self.confidence:.0%} | "
            f"sl={self.stop_loss} tp={self.take_profit})"
        )


# ---------------------------------------------------------------------------
# Abstract Base Strategy
# ---------------------------------------------------------------------------

class BaseStrategy(abc.ABC):
    """
    Abstract base class that all trading strategies must implement.

    Usage pattern in the engine:
        strategy = TrendFollowingStrategy(config)
        signal = strategy.generate_signal(df_primary, df_htf, symbol, regime)
        if signal.is_actionable():
            # Route to trade authorizer → risk manager → order manager
    """

    def __init__(self, config: dict) -> None:
        """
        Args:
            config: Full config dict (config.yaml loaded). Strategies
                    should read their specific parameters from this.
        """
        self._config = config
        self._strategy_id = self.__class__.__name__.lower().replace("strategy", "")

    @property
    def strategy_id(self) -> str:
        """Unique identifier for this strategy (used in trade logging)."""
        return self._strategy_id

    @abc.abstractmethod
    def generate_signal(
        self,
        df: pd.DataFrame,
        symbol: str,
        regime_state: str,
        df_htf: Optional[pd.DataFrame] = None,
    ) -> TradeSignal:
        """
        Analyze market data and generate a trade signal.

        Args:
            df:           Primary timeframe OHLCV DataFrame (e.g. 15m).
                          Index: UTC DatetimeIndex. Columns: open, high, low, close, volume.
                          Minimum length: 100 bars (enforced by caller).
            symbol:       Trading symbol (e.g. "BTC/USDT").
            regime_state: Current regime label (e.g. "BULL_MOMENTUM").
                          Strategies should self-filter: return HOLD if the
                          current regime doesn't match their optimal conditions.
            df_htf:       Higher timeframe DataFrame (e.g. 4H) for confluence.
                          May be None if not available.

        Returns:
            TradeSignal with direction, stop-loss, and take-profit levels.
            Return SignalDirection.HOLD if no edge is found.
        """
        ...

    @abc.abstractmethod
    def get_regime_compatibility(self) -> list[str]:
        """
        Return the list of regime states in which this strategy has edge.

        Example:
            TrendFollowingStrategy returns: ["BULL_MOMENTUM", "BEAR_MOMENTUM"]

        Used by the RegimeEngine.is_strategy_valid() check.
        """
        ...

    def _require_min_bars(self, df: pd.DataFrame, min_bars: int) -> bool:
        """Helper: return False and warn if DataFrame is too short."""
        if len(df) < min_bars:
            return False
        return True

    def _latest(self, series: pd.Series) -> float:
        """Helper: safely get the latest (most recent) value of a Series."""
        if series is None or series.empty:
            return 0.0
        val = series.iloc[-1]
        return float(val) if val is not None and not pd.isna(val) else 0.0

    def _prev(self, series: pd.Series, offset: int = 1) -> float:
        """Helper: safely get a value N bars ago from a Series."""
        if series is None or len(series) <= offset:
            return 0.0
        val = series.iloc[-(offset + 1)]
        return float(val) if val is not None and not pd.isna(val) else 0.0
